### ISSUE TITLE
Auth: 'sign up' page is missing

### ISSUE THREAD

**Issue by lmignon** [locomotivecms/site-templates#3]
@did Looking to the 'auth' demo site, it seems that the 'sign up ' page is missing. Nothing happens if I click on the 'sign up' link.

**Comment by did** [comment]
thanks @lmignon! fixed now: here https://github.com/locomotivecms/site-templates/commit/165cfeb56c779f4a3b839a0bb3bf5171f1d7677c

**Comment by lmignon** [comment]
Thank you @did. By reading the doc I'm just finishing to develop my own page!
